create table teacher (id varchar(20),age varchar(20));
desc teacher;
insert into teacher(id,age) values('01','25');
insert into teacher(id,age) values('02','26');
insert into teacher(id,age) values('03','26');
insert into teacher(id,age) values('04','27');
insert into teacher(id,age) values('05','28');
insert into teacher(id,age) values('06','30');
insert into teacher(id,age) values('07','30');
insert into teacher(id,age) values('08','27');
insert into teacher(id,age) values('09','29');
select* from teacher;
create table teacher2 (id varchar(20),age varchar(20));
desc teacher2;
insert into teacher2(id,age) values('01','35');
insert into teacher2(id,age) values('02','26');
insert into teacher2(id,age) values('03','36');
insert into teacher2(id,age) values('04','47');
insert into teacher2(id,age) values('05','26');
insert into teacher2(id,age) values('06','40');
insert into teacher2(id,age) values('07','30');
insert into teacher2(id,age) values('08','26');
insert into teacher2(id,age) values('09','29');
select * from teacher2;
select age from teacher union select age from teacher2 ;
select age from teacher union all select age from teacher2 ;
select age from teacher intersect select age from teacher2 ;
select age from teacher minus select age from teacher2 ;