create table teacher5 (id varchar(20),age varchar(20));
desc teacher;
insert into teacher5(id,age) values('01','25');
insert into teacher5(id,age) values('02','26');
insert into teacher5(id,age) values('03','26');
insert into teacher5(id,age) values('04','27');
insert into teacher5(id,age) values('05','28');
insert into teacher5(id,age) values('06','30');
insert into teacher5(id,age) values('07','30');
insert into teacher5(id,age) values('08','27');
insert into teacher5(id,age) values('09','29');
select* from teacher5;