create table customer (id varchar(20),name char(20));
desc customer;
insert into customer (id,name) values ('01','a');
insert into customer (id,name) values ('02','b');
insert into customer (id,name) values ('03','c');
insert into customer (id,name) values ('04','d');
insert into customer (id,name) values ('05','e');
select*from customer;
create table orders (id varchar(20),amount varchar(20),customer varchar(20));
desc orders;
insert into orders (id,amount,customer) values ('01','200','03');
insert into orders (id,amount,customer) values ('02','300','07');
insert into orders (id,amount,customer) values ('03','400','05');
insert into orders (id,amount,customer) values ('04','500','08');
insert into orders (id,amount,customer) values ('05','600','02');
select*from orders;
select customer.id,customer.name,orders.amount from customer left join orders on customer.id=orders.customer;
select customer.id,customer.name,orders.amount from customer right join orders on customer.id=orders.customer;
select customer.id,customer.name,orders.amount from customer full outer join orders on customer.id=orders.customer;
